FROM postgres:latest
COPY ./setup-primary.sh /docker-entrypoint-initdb.d/setup-primary.sh
RUN chmod 0666 /docker-entrypoint-initdb.d/setup-primary.sh
COPY ./init-user-db.sh /docker-entrypoint-initdb.d/init-user-db.sh
RUN chmod 0666 /docker-entrypoint-initdb.d/init-user-db.sh
