version: "3"
services:
  pg_primary:
    build: 
      context: ./
      dockerfile: primary.dockerfile
    volumes:
      - pg_data:/var/lib/postgresql/data
    
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PG_REP_USER=rep
      - PG_REP_PASSWORD=postgres
#    networks:
#      default:
#      aliases:
#        - pg_primary
  pg_standby:
    #container_name: pg_standby
    build: 
      context: ./
      dockerfile: standby.dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PG_REP_USER=rep
      - PG_REP_PASSWORD=postgres
#    networks:
#      default:
#      aliases:
#        - pg_standby
volumes:
  pg_data:
